security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: "auto"
        KerberosBundle\User\User: "auto"
        App\Entity\User:
            algorithm: "auto"
            cost: 12

    providers:
        main:
            chain:
                providers: [ldap, users]
        ldap:
            id: kerberos.security.ldap_user_provider
        users:
            id: App\Repository\UserRepository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: main
            entry_point: KerberosBundle\Security\Guard\SF6\KerberosAuthenticator
            custom_authenticators:
                - KerberosBundle\Security\Guard\SF6\KerberosAuthenticator
                - KerberosBundle\Security\Guard\SF6\KerberosFormLoginAuthenticator
            logout:
                path: kerberos_logout
                target: kerberos_login
            switch_user: true
    # role_hierarchy:
    # ROLE_USER: ROLE_READER
    # ROLE_MANAGER: ROLE_USER
    # ROLE_MANAGER_HERITED: ROLE_MANAGER
    # ROLE_ADMIN: ROLE_MANAGER

    access_control:
        - { path: "^/(login|sso|logout)", roles: PUBLIC_ACCESS }
        - { path: "^/", roles: ROLE_USER }
        # - { path: "^/admin", roles: ROLE_ADMIN }
when@dev:
    security:
        providers:
            dev:
                chain:
                    providers: [ldap, memory]
            ldap:
                id: kerberos.security.ldap_user_provider

            memory:
                memory:
                    users:
                        demo:
                            password: "$argon2id$v=19$m=65536,t=4,p=1$GJ/pXkrk3E/UP4b+Jzqt4A$ajOhlRI+Dw7VDPfLKulaD1KbFVuVN+ZPR4CZKsBNNBI"
                            roles: ["ROLE_USER", "ROLE_ADMIN"]
        firewalls:
            main:
                provider: dev
